export const USER_AGENT               = 'depthbomb/node-catbox' as const;
export const CATBOX_API_ENDPOINT      = 'https://catbox.moe/user/api.php' as const;
export const LITTERBOX_API_ENDPOINT   = 'https://litterbox.catbox.moe/resources/internals/api.php' as const;
export const CATBOX_MAX_FILE_BYTES    = 200 * 1024 * 1024;
export const LITTERBOX_MAX_FILE_BYTES = 1024 * 1024 * 1024;
export const CATBOX_REQUEST_TIMEOUT_MS = 5 * 60_000;
export const LITTERBOX_REQUEST_TIMEOUT_MS = 30 * 60_000;
export const MAX_REQUEST_RETRIES      = 2;
export const RETRY_DELAY_MS           = 500;
